language: python
python:
- '2.7'
install: pip install -r requirements.txt
before_script:
- createdb geo
- psql geo <<< "CREATE EXTENSION postgis; CREATE EXTENSION postgis_topology;"
script: python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: Xb5psqzzcf9nPzcNscxhTmMsV+kFF7QXHHoEzxQQN1/yE8fcTvfjk0ozCtqun8kzwnETeTeumNfjt4fnvquqfkUxJf9w6//X8tb4z0ZOP/LxAn5GZPiOiHffsfNUwe6UFlewBB652MhLwZJ2h9/+hgRzupG/vSoVMgzVYQA9SHI=
  app: lr-concept-geo-service
  on:
    repo: LandRegistry/concept-geo-service
    branch: master
  strategy: git
